### ISSUE TITLE
What license is this script under?

### ISSUE THREAD

**Issue by sjl** [lincolnloop/django-cpserver#1]
This seems like exactly the kind of thing I'd love to be able to bundle in an open-source project of my own, but since there's no 'license' file I'm not sure if I can do that (or if I'll have to settle for saying '"install django_cpserver to use this").  Could you possibly add a LICENSE.txt or something similar?

**Comment by lincolnloop** [comment]
Added license
losed by 19739bea057d824d9cd6c10c4caec622e8e1c0b9
