### ISSUE TITLE
Need a way to configure server

### ISSUE THREAD

**Issue by quantoid** [lincolnloop/django-cpserver#5]
There's no obvious way to configure the CherryPy server, e.g. to serve static files as well as the Django WSGI application. It would be useful to have an option to pass in the filename of a server config file.

**Comment by quantoid** [comment]
I know this project hasn't been updated for a while, but it's really useful so I'm hoping this request might revive activity.

**Comment by kisna72** [comment]
To serve static files, you can add the static url in your urls. 

`static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)`

Keep in mind though that this will not work in production (i.e. when Debug = False in django.) The best way to serve files is by wither using gunicorn (in linux systems) or nginx (works in linux and windows).

Thanks

**Comment by kisna72** [comment]
Also Don't forget to run `python manage.py collectstatic`

**Comment by quantoid** [comment]
Switched to https://pypi.python.org/pypi/django-wsgiserver
